INSERT INTO EMPLOYEE(EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT)
VALUES ('Akki', 10000, 'Depart1');

INSERT INTO EMPLOYEE(EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT)
VALUES ('Ak', 20000, 'Depart2');